GET http://localhost:3001/api/blogs HTTP/1.1

###

POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: : application/json

{
    {
        "title": "the rest blog",
        "author": "suudi",
        "url": "456",
        "likes": "123",
        "userId": "661d30f5f7d99b5446d2cc02"
    }
}